workspace = { members = [ "crates/chumsky_semver","crates/wit_format"] }
[package]
name = "generate_wit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
